# Generated by Django 5.1 on 2024-08-12 15:27

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=200)),
                ('company_location', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=255)),
                ('company_twitter', models.URLField(blank=True, default=builtins.any, max_length=100, null=True)),
                ('company_facebook', models.URLField(blank=True, default=builtins.any, max_length=100, null=True)),
                ('company_instagram', models.URLField(blank=True, default=builtins.any, max_length=100, null=True)),
                ('company_linkedin', models.URLField(blank=True, default=builtins.any, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'infos',
                'verbose_name_plural': 'infos',
                'db_table': 'infos',
                'managed': True,
            },
        ),
    ]
