# Generated by Django 5.1 on 2024-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_infos_company_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_picture', models.ImageField(height_field='200px', upload_to='static/uploads')),
                ('service_title', models.CharField(max_length=50)),
                ('service_description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'services',
                'verbose_name_plural': 'services',
                'db_table': 'services',
                'managed': True,
            },
        ),
    ]
