# Generated by Django 5.1 on 2024-08-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_servicesmodel_service_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmodel',
            name='service_picture',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
