# Generated by Django 5.1 on 2024-08-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_servicesmodel_service_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=50)),
                ('about_content', models.TextField()),
                ('about_image', models.ImageField(upload_to='uploads')),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'about',
                'db_table': 'about',
                'managed': True,
            },
        ),
    ]
