# Generated by Django 5.1 on 2024-08-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_aboutmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_title', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('team_image', models.ImageField(upload_to='uploads')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'team',
                'db_table': 'team',
                'managed': True,
            },
        ),
    ]
