# Generated by Django 5.1 on 2024-08-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_teammodel_team_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamModel',
        ),
    ]
