# Generated by Django 5.1 on 2024-08-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_teammodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_picture', models.ImageField(upload_to='uploads')),
                ('team_role', models.CharField(max_length=50)),
            ],
        ),
    ]
